name: Website Deployment
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of deployablle artifacts files
        required: true
        default: dist
        type: string
    secrets:
      some-secret:
        required: false
    outputs:
      result:
        description: The result  of the deployment operation
        value: ${{jobs.deploy.outputs.outcome}}
jobs:
  deploy:
    outputs:
      outcome: ${{steps.set-result.outputs.step-result}}
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{inputs.artifact-name}}
      - name: Output Contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
      - name: Set result Output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
